# Generated by Django 3.1.3 on 2020-11-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bookinfo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorandbook',
            options={'verbose_name': 'Author and Book', 'verbose_name_plural': 'Authors and Books'},
        ),
    ]
