# Generated by Django 3.1.3 on 2020-11-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201122_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eamil',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.BooleanField(default=True),
        ),
    ]
