# Generated by Django 3.1.3 on 2020-11-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='eamil',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
