# Generated by Django 3.1.3 on 2020-11-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201124_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LibUser',
        ),
        migrations.CreateModel(
            name='LibAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.libuser')),
            ],
            options={
                'verbose_name': 'Library_Admin',
                'verbose_name_plural': 'Library_Admins',
            },
        ),
    ]
