# Generated by Django 3.1.3 on 2020-11-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201124_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_status',
        ),
        migrations.AddField(
            model_name='libadmin',
            name='book_status',
            field=models.BooleanField(default='True', null=True),
        ),
    ]
