# Generated by Django 3.1.3 on 2020-11-25 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201125_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='libadmin',
            name='give_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 5, 12, 0, 36, 49600)),
        ),
    ]
