# Generated by Django 3.1.3 on 2020-11-25 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201125_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libadmin',
            name='give_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 5, 13, 19, 45, 561594)),
        ),
        migrations.AlterField(
            model_name='libadmin',
            name='take_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
