# Generated by Django 3.1.3 on 2020-11-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201125_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libadmin',
            name='give_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libadmin',
            name='take_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
