# Generated by Django 3.1.3 on 2020-11-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201127_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorandbook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authorandbook',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='AuthorandBook',
        ),
    ]
