# Generated by Django 3.1.3 on 2020-11-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201127_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libuser',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
