# Generated by Django 3.1.3 on 2020-11-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20201127_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libadmin',
            name='take_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
