# Generated by Django 3.1.3 on 2020-11-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201129_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='libuser',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
