# Generated by Django 3.1.3 on 2020-11-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_libuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libuser',
            name='name',
        ),
    ]
