# Generated by Django 3.1.3 on 2020-11-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_libuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='received',
            field=models.BooleanField(null=True),
        ),
    ]
