# Generated by Django 3.1.3 on 2020-11-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_book_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='received',
        ),
        migrations.AddField(
            model_name='libadmin',
            name='received',
            field=models.BooleanField(null=True),
        ),
    ]
