# Generated by Django 3.1.3 on 2020-11-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20201129_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libadmin',
            old_name='received',
            new_name='returned',
        ),
    ]
