# Generated by Django 3.1.3 on 2020-11-30 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20201130_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libadmin',
            name='give_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 10, 14, 9, 26, 746612)),
        ),
        migrations.AlterField(
            model_name='libadmin',
            name='take_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
