# Generated by Django 3.1.3 on 2020-11-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20201130_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libadmin',
            name='give_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libadmin',
            name='take_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
