# Generated by Django 3.1.3 on 2020-11-30 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20201130_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libadmin',
            name='give_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 30, 14, 34, 0, 979062), verbose_name=datetime.datetime(2020, 12, 10, 14, 34, 0, 979062)),
        ),
    ]
