# Generated by Django 3.1.3 on 2020-11-30 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20201130_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 14, 36, 32, 588346)),
        ),
        migrations.AlterField(
            model_name='libadmin',
            name='give_date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2020, 12, 10, 14, 36, 32, 588346)),
        ),
    ]
