# Generated by Django 3.1.3 on 2020-11-30 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20201130_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 14, 38, 4, 354528)),
        ),
        migrations.AlterField(
            model_name='libadmin',
            name='give_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 12, 10, 14, 38, 4, 354528)),
        ),
    ]
