# Generated by Django 3.1.3 on 2020-11-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20201130_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='libadmin',
            name='take_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libadmin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='libadmin',
            name='give_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
