# Generated by Django 3.1.3 on 2020-12-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20201201_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libadmin',
            name='book_status',
        ),
        migrations.AddField(
            model_name='book',
            name='book_status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
