# Generated by Django 3.1.3 on 2020-12-01 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20201201_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libadmin',
            name='give_date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2020, 12, 11, 21, 29, 38, 845472)),
        ),
    ]
