# Generated by Django 3.1.3 on 2020-12-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20201201_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libadmin',
            name='give_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
